"""Added assessment column to MiningLocation

Revision ID: 3da8f6739a9a
Revises: 
Create Date: 2024-09-09 20:18:25.847641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3da8f6739a9a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mining_location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('type_of_mining', sa.String(length=100), nullable=False),
    sa.Column('tenure', sa.Integer(), nullable=True),
    sa.Column('affect_radius', sa.Float(), nullable=True),
    sa.Column('impact_scale', sa.Float(), nullable=True),
    sa.Column('water_quality', sa.Float(), nullable=True),
    sa.Column('air_quality', sa.Float(), nullable=True),
    sa.Column('soil_quality', sa.Float(), nullable=True),
    sa.Column('biodiversity', sa.Text(), nullable=True),
    sa.Column('socioeconomic_index', sa.Text(), nullable=True),
    sa.Column('job_count_index', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cycle_status', sa.String(length=50), nullable=True),
    sa.Column('assessment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('user_type', sa.String(length=50), nullable=False),
    sa.Column('job_count', sa.Integer(), nullable=True),
    sa.Column('nearest_location_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['nearest_location_id'], ['mining_location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('regulator_id', sa.Integer(), nullable=True),
    sa.Column('permit_details', sa.Text(), nullable=False),
    sa.Column('issue_date', sa.DateTime(), nullable=True),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['mining_location.id'], ),
    sa.ForeignKeyConstraint(['regulator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('permit')
    op.drop_table('user')
    op.drop_table('mining_location')
    # ### end Alembic commands ###
